### PR TITLE
Javascript javascript3 week1

### PR DESCRIPTION
**Pull request by Darya-s**
Can not reach link for gif API

### CODE REVIEW

**Review by florinmaticu — COMMENTED** [review]
The gipy code doesn't seem to work. see picture attached. Also you accidentaly added your previous homeworks in this merge request. You can remove them and add another commit to the mr.
image

**Comment by florinmaticu** [comment]
For the weather application, the code doesn't display the data for a city like `Rome`. You can use https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer to test your implementations.
image

**Comment by Darya-s** [comment]
> * The gipy code doesn't seem to work. see picture attached. Also you accidentaly added your previous homeworks in this merge request. You can remove them and add another commit to the mr.
>   image

Hi florinmaticu , I ve tried to delete previous homework I hope it works. I noticed that it is not working, but I do not understand why, I guess something wrong with API, as it gives me 404 Error , server not found.

**Comment by Darya-s** [comment]
> * For the weather application, the code doesn't display the data for a city like `Rome`. You can use https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer to test your implementations.
>   image

It does not display for others city. Because I left only to take data from current location. The code for search city is commented.

**Comment by florinmaticu** [comment]
In case fetching data from server doesn't work then you can catch the error and log it or inform the user that something went wrong. 

For example :
const data = { username: 'example' };

fetch('https://example.com/profile', {
  method: 'POST', // or 'PUT'
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify(data),
})
.then(response => response.json())
.then(data => {
  console.log('Success:', data);
})
.catch((error) => {
  console.error('Error:', error);
});

**Review by florinmaticu — APPROVED** [review]
Best of luck in the next classes. I have added a small comment that is more an advice

**Pull request merged**
